config/routes.rb
Rails.application.routes.draw do


  devise_for :admin,skip: [:registrations,:passwords,], controllers: {
  registrations: "admin/registrations",
  sessions: 'admin/sessions'
}

  devise_for :customers,skip: [:passwords] ,controllers: {
  registrations: "customers/registrations",
  sessions: 'customers/sessions'
  }

  get '/about' => 'homes#about'
  root to: 'homes#top'


  namespace :admin do
    resources :customers, only: [:show, :edit, :update, :index]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders,only: [:index, :show, :update]
    resources :order_details,only: [:update]
  end

  scope module: :customers do
    resources :customers, only: [:edit, :update]
    get "customers/my_page" => "customers#show", as: "my_page"
    resources :items, only: [:index, :show]
    get   "/customers/:id/quit" => "customers#quit"
    patch "customers/:id/out" => "customers#out", as: "out"
    resources :cart_items, only: [:index, :update, :create, :destroy]
    delete '/cart_items' => 'cart_items#destroy_all', as: :destroy_all_cart_items
    resources :addresses, except: [:show, :new]

    get   '/orders/complete' => 'orders#complete', as: :complete
    post '/orders/confirm' => 'orders#confirm', as: :confirm
    resources :orders, only: [:new, :index, :show, :create,  :complete]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end


  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :fist_name, presence: true
  validates :last_name, presence: true
  validates :fist_name_kana, format: { with:/\A[ァ-ヶー－]+\z/ }, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code,length: { minimum: 7 }, presence: true
  validates :address,presence: true
  validates :phon_number, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_deposit: 0, payment_confirmation: 1, in_production: 2, preparing_ship: 3, shipped_items: 4 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customer = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
     if  @customer.update(customer_params)
    redirect_to  admin_customer_path(@customer.id)
     else
    render edit_admin_customer_path
     end
  end

private

  def customer_params
    params.require(:customer).permit(:fist_name, :last_name,:fist_name_kana, :last_name_kana, :email, :address, :phon_number, :postal_code, :is_deleted, :page)
  end

  def if_not_admin
    redirect_to root_path unless current_.admin?
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders =Order.all.page(params[:page]).reverse_order
  end

  def show
    @order = Order.find(params[:id])
    @order_details =@order.order_details
    
  end
  
  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    if @order.update(order_params)
      if params[:order][:status] == "payment_confirmation"
        @order_details.each do |order_detail|
          order_detail.making_status = "waiting_production"
          order_detail.save
        end
        
      end
        redirect_to request.referer
    end
  end
  
private
  def order_params
    params.require(:order).permit(:status)
  end


end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController

  def index
    @items = Item.all.page(params[:page])
  end

  def show
    @items = Item.all
    @item =Item.find(params[:id])
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :price, :is_active, :description)
  end
end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController

  def index
    @address = Address.new
    @addresses =Address.all
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @address.save
    redirect_to request.referer
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    @address.update(address_params)
    redirect_to  addresses_path
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to request.referer
  end

  private
  def address_params
    params.require(:address).permit(:name, :address, :postal_code,:customer_id)
  end

end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
  def index
    @cart_items = current_customer.cart_items.all
    @total_price= @cart_items.sum { |cart_item| cart_item.item.price * cart_item.amount }

  end

	def update
	  @cart_item = CartItem.find(params[:id])
    @cart_item.update(amount: params[:cart_item][:amount].to_i)
    # @price = sub_total(@cart_item).to_s(:delimited)
    # @cart_items = current_cart
    # @total = amount(@cart_items).to_s(:delimited)
     redirect_to cart_items_path
	end

	def create
    @cart_item = CartItem.new(params_cart_item)
    @cart_item.customer_id = current_customer.id
    @cart_items=current_customer.cart_items.all
    @cart_items.each do |cart_item|
    if  cart_item.item_id==@cart_item.item_id
        new_amount = cart_item.amount + @cart_item.amount
        cart_item.update_attribute(:amount, new_amount)
        @cart_item.delete
    end
  end
    @cart_item.save
    redirect_to cart_items_path

	end

	def destroy_all
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    redirect_to cart_items_path
	end

	def destroy
	  @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
	end

  private

  def params_cart_item
    params.require(:cart_item).permit(:amount, :item_id, :customer_id)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  def show
    @customer = current_customer
     if @customer == current_customer
     else
     redirect_to my_page_path
     end
  end

  def edit
    @customer = Customer.find(params[:id])
     if @customer == current_customer
     else
     redirect_to my_page_path
     end
  end

  def quit
    @customer = Customer.find(params[:id])
  end

  def out
    @customer = Customer.find(params[:id])
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  def update
    @customer = Customer.find(params[:id])
     if  @customer.update(customer_params)
       flash[:notice] = "have updated customer successfully."
    redirect_to my_page_path
     else
    render :edit
     end
  end
private

  def customer_params
    params.require(:customer).permit(:fist_name, :last_name,:fist_name_kana, :last_name_kana, :email, :address, :phon_number, :postal_code)
  end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page])
  end

  def show
    @items = Item.all
    @item =Item.find(params[:id])
    @cart_item =CartItem.new
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :price, :is_active, :description)
  end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController


  def new
    @order = Order.new
  end

  def create
    cart_items = current_customer.cart_items.all
    #binding.pry
    @order = current_customer.orders.new(order_params)
    @order.shipping_cost = 800
    #status = enumで定義したやつを入れてあげる
    if @order.save
      #binding.pry
      cart_items.each do |cart|
        order_detail = OrderDetail.new
        order_detail.item_id = cart.item_id
        order_detail.order_id = @order.id
        order_detail.amount = cart.amount
        order_detail.price = cart.item.price
        #making_status = enumで定義したやつを入れてあげる
        order_detail.save
      end
      cart_items.destroy_all
      redirect_to complete_path
    else
      @order = Order.new(order_params)
      render :new
    end
  end

  def confirm
    @order = Order.new(order_params)
      if params[:order][:address_number] == "1"
        @order.name = current_customer.fist_name + current_customer.last_name
        @order.address = current_customer.address
        @order.postal_code = current_customer.postal_code
      elsif params[:order][:address_number] == "2"
        @address = Address.find(params[:order][:address_id])
        @order.postal_code = @address.postal_code
        @order.name = @address.name
        @order.address =@address.address
      elsif params[:order][:address_number] == "3"
        @order.postal_code =params[:order][:postal_code]
        @order.name = params[:order][:address_name]
        @order.address = params[:order][:address]
      else
      redirect_to confirm_path
      end
    @cart_items = current_customer.cart_items.all
    @total = @cart_items.inject(0) { |sum, item| sum + item.subtotal }

  end
  def complete
  end

  def index
    @orders = current_customer.orders.all
  end

  def show
    @order =Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:name, :address, :total_payment, :payment_method, :postal_code)
  end

  def address_params
    params.require(:order).permit(:name, :address)
  end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

protected
  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && (@customer.is_deleted == false)
        redirect_to new_customer_registration , notice:"退会済みです。再度ご登録をしてご利用ください。"
      else
        flash[:notice] = "項目を入力してください"
        redirect_to new_customer_sessions
      end
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customers/addresses_helper.rb
module Customers::AddressesHelper
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper
end

app/views/customers/orders/complete.html.erb
<div class="row col-xs-12 center-block">
  <h1 class="text-center thanx">ご購入ありがとうございました！</h1><br>
</div>

app/views/customers/orders/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-offset-1">
      <!-- ユーザーに確認してもらうための表示です -->
        <%#= cart.item.address %>
        <table class="table">
            <thead>
                <tr>
                  <th>商品名</th>
                  <th>単価(税込み)</th>
                  <th>数量</th>
                  <th>小計</th>
                </tr>
            </thead>
            <tbody>
              <% @cart_items.each do |cart| %>
                <tr>
                  <td><%= cart.item.name %> <!-- 商品名 --></td>
                  <td><%= (cart.item.price).to_s(:delimited) %><!-- 金額 --></td>
                  <td><%= cart.amount %> <!-- 個数 --></td>
                  <td><%= (cart.item.price*cart.amount).to_s(:delimited) %> <!-- 小計 --></td>
                </tr>
              <% end %>
            </tbody>
        </table>
      <div class="col-xs-3">
        <table>
          <tr>
            <th class="info">送料</th>
            <td class="info">800<%#= @order.shipping_cost %><%#= @order.shipping_cost.to_s(:delimited) %></td>
          </tr>
          <tr>
            <th class="info">商品合計</th>
            <td><%= @total.to_s(:delimited) %> <!-- お買い物の合計金額 <--></td>
          </tr>
          <tr>
            <th class="info">請求金額</th>
            <td><%= (800 + @total).to_s(:delimited)%></td>
          </tr>
        </table>
        <table>
          <tr class="info">
            <th class= "info">支払い方法</th>
              <td><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <th class= "info">お届け先</th>
              <td><%= @order.address %></td>
              <td><%= @order.postal_code %></td>
              <td><%= @order.name %></td>
          </tr>
        </table>
      </div>


      <!-- ユーザーには注文確定ボタンだけ表示します -->
      <%= form_with model: @order, url: orders_path, local: true do |f| %>
        <%= f.hidden_field :name, value: @order.name %>
        <%= f.hidden_field :address, value: @order.address %>
        <%= f.hidden_field :postal_code, value: @order.postal_code %>
        <%= f.hidden_field :payment_method, value: @order.payment_method %>
        <%= f.hidden_field :shipping_cost, value: @order.shipping_cost %>
        <%= f.hidden_field :total_payment, value: @total + 800 %>
        <%= f.submit "注文を確定する" %>
      <% end %>
    </div>
  </div>
</div>

app/views/customers/orders/index.html.erb
<div class="container">
  <div calss="row">
    <div class="col-xs-12">
      <h2 class="head-line title_h2 text-center">注文履歴一覧</h2>
        <% if @orders.present? %>
          <table class="table table-hover table-bordered table-condensed">
            <thead>
              <tr class="info">
                <th><i class="fas fa-calendar-day"></i>注文日</th>
                <th>配送先</th>
                <th>注文商品</th>
                <th>支払金額</th>
                <th>ステータス</th>
                <th>注文詳細</th>
              </tr>
            </thead>
            <tbody>
              <% @orders.each do |order| %>
                <tr>
                  <td>
      		          <%= order.created_at.strftime('%Y/%m/%d') %>
      		        </td>
      		        <td class="text-left">
      		          <%= order.postal_code %><br>
      		          <%= order.address %><br>
      		          <%= order.name %>
      		        </td>
      		        <td>
      		          <% order.order_details.each do |order_detail| %>
      		          	<%= order_detail.item.name %><br>
      		          <% end %>
      		        </td>
      		        <td class="text-right">
      		          <%= order.total_payment.to_s(:delimited) %>円
      		        </td>
      		        <td>
      		          <%= order.status_i18n %>
      		        </td>
           	      <td>
         	          <%= link_to "注文詳細", order_path(order), class: "glyphicon glyphicon-zoom-in btn btn-success" %>
         	        </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p>注文履歴がありません。</p>
        <% end %>
      </div>
    </div>
</div>

app/views/customers/orders/new.html.erb
<div class="container">
  <div class="row">
     <div class="col-xs-offset-1">

      <!-- @order でラジオボタンを使って情報を送ります -->
      <%= form_with model: @order, url:  confirm_path, local: true do |f| %>
      <h3>支払い方法</h3>
      <div class="col-xs-10 radio">
        <%= f.radio_button :payment_method, Order.payment_methods.key(0) %>
        <%= f.label :payment_method, Order.payment_methods_i18n[:credit_card] %>
      </div>
      <div class="col-xs-10 radio">
        <%= f.radio_button :payment_method, Order.payment_methods.key(1) %>
        <%= f.label :payment_method, Order.payment_methods_i18n[:transfer]%>

      </div>
      <h3>お届け先</h3>
        <div class="col-xs-10 radio">
      <!-- customer テーブルに登録されている住所の場合です -->
        <%= f.radio_button :address_number, 1 %> <!-- address_number と定義して1～3の番号を check に送ります -->
        <%= f.label :address_number_1, "ご自身の住所" %>
        <%= current_customer.address %>
        <%= current_customer.fist_name %>
        <%= current_customer.last_name %>

        </div>
        <div class="col-xs-10 radio">
      <!-- 登録されたaddressから選んでもらう場合です -->
        <%= f.radio_button :address_number, 2 %>
        <%= f.label :address_number_2, "登録先の住所" %>
        <%#= f.collection_select(:registered, current_customer.addresses.all, :id, :address %>
        <%= f.select :address_id, options_from_collection_for_select(Address.all, :id, :full_address) %>
      <!-- registered として current_customer.address.all で取得した id を送ります。
           ユーザーに表示して選択してもらうのは address です -->
      <!-- ドロップダウンを選択したら自動でラベルも選択されるようにしたかったのですが、現状ではわかりませんでした -->
        </div>
        <div class="new-address col-xs-10 radio">
          <div class="field form-group col-xs-11">
          <!-- 新しい住所を追加する場合です -->
            <%= f.radio_button :address_number, 3 %>
            <%= f.label :address_number_3, "新しいお届け先" %>
          </div>
          <div class="field form-group col-xs-11">
            <%= f.label :postal_code, "郵便番号" %>
            <%= f.text_field :postal_code %>
          <!-- 選んでもらったデータを送ります -->
          </div>
          <div class="field form-group col-xs-11">
            <%= f.label :address, "住所" %>
            <%= f.text_field :address %>
          </div>
          <div class="field form-group col-xs-11">
            <%= f.label :address_name, "宛名" %>
            <%= f.text_field :address_name %>
          <!-- 選んでもらったデータを送ります -->
            <%= f.submit "確認画面へ進む", class: "btn btn-success col-xs-5" %>
          </div>
          <% end %>
          </div>
        </div>
      </div>
  </div>

app/views/customers/orders/show.html.erb
<div class="container">
  <h2 class="head-line title_h2 text-center">注文履歴詳細</h2>
  <div calss="row">
      <div class="col-md-4">
      	<strong><i class="far fa-user"></i>注文情報</strong>
    	    <table class="md3 table">
            <tbody>
                <tr>
                  <th class="info">注文日</th>
            	    <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
                </tr>
                <tr>
                  <th class="info">配送先</th>
                  <td class="text-left"><%= @order.postal_code %><br>
                  	  <%= @order.address %><br>
                  	  <%= @order.name %>
                  </td>
                </tr>
                <tr>
                  <th class="info">支払方法</th>
                  <td class="text-left"><%= @order.payment_method_i18n %></td>
                </tr>
                <tr>
                  <th class="info">ステータス</th>
                  <td class="text-left"><%= @order.status_i18n %></td>
                </tr>
            </tbody>
          </table>
      </div>

      <div class='flex'>
        <strong><i class="fas fa-yen-sign"></i>請求情報</strong>
          	<table class="table">
              <tr>
                <th class="info">商品合計</th>
                <td class="text-right col-3"><%= @order.total_payment.to_s(:delimited) %>円</td>
              </tr>
              <tr>
                <th class="info">配送料</th>
                <td class="text-right col-3">800<%#= @order.shipping_cost.to_s(:delimited) %>円</td>
              </tr>
              <tr>
                <th class="info">ご請求金額</th>
                <td class="text-right col-3"><%= (800 + @order.total_payment).to_s(:delimited)%>円</td>
              </tr>
          </table>
      </div>
      <div class="col-5">
      	<strong><i class="fas fa-store"></i>注文内容</strong>
          <table class="table">
          	<thead>
      	      <tr class="info">
      	      	<th>商品</th>
      	        <th>単価(税込)</th>
      	      	<th>個数</th>
      	      	<th>小計</th>
      	      </tr>
          	</thead>
          	<tbody>
            	<% @order.order_details.each do |order_detail| %>
            	<tr>
                <td><%= order_detail.item.name %> <!-- 商品名 --></td>
                <td><%= (order_detail.item.price).to_s(:delimited) %><!-- 単価 --></td>
                <td><%= order_detail.amount %> <!-- 個数 --></td>
                <td><%= (order_detail.item.price*order_detail.amount).to_s(:delimited) %> <!-- 小計 --></td>
            	</tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
  </div>