config/routes.rb
Rails.application.routes.draw do


  devise_for :admin,skip: [:registrations,:passwords,], controllers: {
  registrations: "admin/registrations",
  sessions: 'admin/sessions'
}

  devise_for :customers,skip: [:passwords] ,controllers: {
  registrations: "customers/registrations",
  sessions: 'customers/sessions'
  }

  get '/about' => 'homes#about'
  root to: 'homes#top'


  namespace :admin do
    resources :customers, only: [:show, :edit, :update, :index]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders,only: [:index, :show, :update]
    resources :order_details,only: [:update]
  end

  scope module: :customers do
    resources :customers, only: [:edit, :update]
    get "customers/my_page" => "customers#show", as: "my_page"
    resources :items, only: [:index, :show]
    get   "/customers/:id/quit" => "customers#quit"
    patch "customers/:id/out" => "customers#out", as: "out"
    resources :cart_items, only: [:index, :update, :create, :destroy]
    delete '/cart_items' => 'cart_items#destroy_all', as: :destroy_all_cart_items
    resources :addresses, except: [:show, :new]

    get   '/orders/complete' => 'orders#complete', as: :complete
    post '/orders/confirm' => 'orders#confirm', as: :confirm
    resources :orders, only: [:new, :index, :show, :create,  :complete]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end


  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :fist_name, presence: true
  validates :last_name, presence: true
  validates :fist_name_kana, format: { with:/\A[ァ-ヶー－]+\z/ }, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code,length: { minimum: 7 }, presence: true
  validates :address,presence: true
  validates :phon_number, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customer = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
     if  @customer.update(customer_params)
    redirect_to  admin_customer_path(@customer.id)
     else
    render edit_admin_customer_path
     end
  end

private

  def customer_params
    params.require(:customer).permit(:fist_name, :last_name,:fist_name_kana, :last_name_kana, :email, :address, :phon_number, :postal_code, :is_deleted, :page)
  end

  def if_not_admin
    redirect_to root_path unless current_.admin?
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController

  def index
    @items = Item.all.page(params[:page])
  end

  def show
    @items = Item.all
    @item =Item.find(params[:id])
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :price, :is_active, :description)
  end
end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController

  def index
    @address = Address.new
    @addresses =Address.all
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @address.save
    redirect_to request.referer
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    @address.update(address_params)
    redirect_to  addresses_path
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to request.referer
  end

  private
  def address_params
    params.require(:address).permit(:name, :address, :postal_code,:customer_id)
  end

end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
  def index
    @cart_items = current_customer.cart_items.all
    @total_price= @cart_items.sum { |cart_item| cart_item.item.price * cart_item.amount }

  end

	def update
	  @cart_item = CartItem.find(params[:id])
    @cart_item.update(amount: params[:cart_item][:amount].to_i)
    # @price = sub_total(@cart_item).to_s(:delimited)
    # @cart_items = current_cart
    # @total = amount(@cart_items).to_s(:delimited)
     redirect_to cart_items_path
	end

	def create
    @cart_item = CartItem.new(params_cart_item)
    @cart_item.customer_id = current_customer.id
    @cart_items=current_customer.cart_items.all
    @cart_items.each do |cart_item|
    if  cart_item.item_id==@cart_item.item_id
        new_amount = cart_item.amount + @cart_item.amount
        cart_item.update_attribute(:amount, new_amount)
        @cart_item.delete
    end
  end
    @cart_item.save
    redirect_to cart_items_path

	end

	def destroy_all
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    redirect_to cart_items_path
	end

	def destroy
	  @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
	end

  private

  def params_cart_item
    params.require(:cart_item).permit(:amount, :item_id, :customer_id)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  def show
    @customer = current_customer
     if @customer == current_customer
     else
     redirect_to my_page_path
     end
  end

  def edit
    @customer = Customer.find(params[:id])
     if @customer == current_customer
     else
     redirect_to my_page_path
     end
  end

  def quit
    @customer = Customer.find(params[:id])
  end

  def out
    @customer = Customer.find(params[:id])
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  def update
    @customer = Customer.find(params[:id])
     if  @customer.update(customer_params)
       flash[:notice] = "have updated customer successfully."
    redirect_to my_page_path
     else
    render :edit
     end
  end
private

  def customer_params
    params.require(:customer).permit(:fist_name, :last_name,:fist_name_kana, :last_name_kana, :email, :address, :phon_number, :postal_code)
  end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page])
  end

  def show
    @items = Item.all
    @item =Item.find(params[:id])
    @cart_item =CartItem.new
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :price, :is_active, :description)
  end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController


  def new
    @order = Order.new
  end

  def create
    cart_items = current_customer.cart_items.all
    #binding.pry
    @order = current_customer.orders.new(order_params)
    @order.shipping_cost = 800
    #status = enumで定義したやつを入れてあげる
    if @order.save
      #binding.pry
      cart_items.each do |cart|
        order_detail = OrderDetail.new
        order_detail.item_id = cart.item_id
        order_detail.order_id = @order.id
        order_detail.amount = cart.amount
        order_detail.price = cart.item.price
        #making_status = enumで定義したやつを入れてあげる
        order_detail.save
      end
      cart_items.destroy_all
      redirect_to complete_path
    else
      @order = Order.new(order_params)
      render :new
    end
  end

  def confirm
    @order = Order.new(order_params)
      if params[:order][:address_number] == "1"
        @order.name = current_customer.fist_name + current_customer.last_name
        @order.address = current_customer.address
        @order.postal_code = current_customer.postal_code
      elsif params[:order][:address_number] == "2"
        @address = Address.find(params[:order][:address_id])
        @order.postal_code = @address.postal_code
        @order.name = @address.name
        @order.address =@address.address
      elsif params[:order][:address_number] == "3"
        @order.postal_code =params[:order][:postal_code]
        @order.name = params[:order][:address_name]
        @order.address = params[:order][:address]
      else
      redirect_to confirm_path
      end
    @cart_items = current_customer.cart_items.all
    @total = @cart_items.inject(0) { |sum, item| sum + item.subtotal }

  end
  def complete
  end

  def index
    @orders = current_customer.orders.all
  end

  def show
    @order =Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:name, :address, :total_payment, :payment_method, :postal_code)
  end

  def address_params
    params.require(:order).permit(:name, :address)
  end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

protected
  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && (@customer.is_deleted == false)
        redirect_to new_customer_registration , notice:"退会済みです。再度ご登録をしてご利用ください。"
      else
        flash[:notice] = "項目を入力してください"
        redirect_to new_customer_sessions
      end
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers/addresses_helper.rb
module Customers::AddressesHelper
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/customers/orders_helper.rb
module Customers::OrdersHelper
end

app/views/admin/customers/edit.html.erb
<div class="form-inline">
  <div class="offset-md-1">
    <h4 class="font-weight-bold"><%= "#{@customer.fist_name}" "#{@customer.last_name}" %></h4>
  </div>
    <h4>さんの</h4>
    <h4 class="font-weight-bold"><%= "会員情報編集" %></h4>
  </div>
</div>
</h5>
<div class= container >
   <div class="d-flex align-items-center justify-content-center" >
        <%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>
        <div class = "row">
             <div class = "col-4" >
                <%= f.label :氏名  %>
             </div>
             <div class = "col-4" >
                <%= f.text_field :fist_name, autofocus: true, class: "form-control" %>
             </div>
             <div class = "col-4" >
                <%= f.text_field  :last_name, autofocus: true, class: "form-control" %>
             </div>
        </div>
        
        <div class = "row">
             <div class = "col-4" >
                <%= f.label :フリガナ  %>
             </div>
             <div class = "col-4" >
                <%= f.text_field :fist_name_kana, autofocus: true, class: "form-control" %>
             </div>
             <div class = "col-4" >
                <%= f.text_field  :last_name_kana, autofocus: true, class: "form-control" %>
             </div>
        </div>
   
        <div class = "row">
             <div class = "col-4" >
                <%= f.label :郵便番号  %>
             </div>
             <div class = "col-4" >
                <%= f.text_field :postal_code, autofocus: true, class: "form-control" %>
             </div>
        </div>
        <div class = "row">
             <div class = "col-4" >
                <%= f.label :住所  %>
             </div>
             <div class = "col-4" >
                <%= f.text_field :postal_code, autofocus: true, class: "form-control" %>
             </div>
        </div>
        <div class = "row">
             <div class = "col-4" >
                <%= f.label :電話番号 %>
             </div>
             <div class = "col-4" >
                <%= f.text_field :phon_number, autofocus: true, class: "form-control" %>
             </div>
        </div>
        <div class = "row">
             <div class = "col-4" >
                <%= f.label :メールアドレス  %>
             </div>
             <div class = "col-4" >
                <%= f.text_field :email, autofocus: true, class: "form-control" %>
             </div>
        </div>

        <div class="row">
            <div class="col-4 ">
                <%= f.radio_button :is_deleted, :true %>退会
                <%= f.radio_button :is_deleted, :false %>有効
            </div>
          </div>


 <div class="form-inline">
    <div class="form-group" style="height:80px">
    <%= f.submit "編集内容を保存", class: "ml-2 btn px-5  btn-success font-weight-bold" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/admin/customers/index.html.erb
   <div class="col-md-8 offset-md-1">
     <div class="font-weight-bold">
      <h2>会員一覧</h2>
     </div>
     <table class="table table-hover table-inverse">
       <thead>
          <tr>
       　   <th>会員ID</th>
           <th>氏名</th>
           <th>メールアドレス</th>
           <th>ステータス</th>
           </tr>
        </thead>
      <tbody>
          <% @customer.each do |customer| %>
        <tr>
        <td><%= customer.id %>
      <div class="form-inline">
        <div class="form-group">
          <td><%= link_to "#{customer.fist_name}　#{customer.last_name}",admin_customer_path(customer.id) %></td>
        </div>
      </div>
      <td><%= customer.email %></td>
        <td>
          <% if customer.is_deleted == true %>
          <div class="form-inline text-muted">
            退会
         </div>
          <% else %>
          <div class="form-inline text-success">
            有効
          </div>
          <% end %>
          <% end %>
          </td>
        </tr>
        </tbody>
      </table>
      <div class="d-flex align-items-center justify-content-center" >
          <%= paginate @customer %>
      </div>
    </div>

app/views/admin/customers/show.html.erb
<div class="form-inline">
  <div class="offset-md-1">
    <h4 class="font-weight-bold"><%= "#{@customer.fist_name}" "#{@customer.last_name}" %></h4>
  </div>
    <h4>さんの</h4>
    <h4 class="font-weight-bold"><%= "会員詳細" %></h4>
  </div>
</div>

<div class="container">
  <div class="form-inline">
    <div class="form-group">
    　<lavel>会員ID</lavel>
      <div class="ml-2 d-flex align-items-center justify-content-center" style="height:60px" >
      <%= "#{@customer.id}" %>
      </div>
     </div>
  </div>
 <div class="form-inline">
    <div class="form-group">
    　<lavel>氏名</lavel>
      <div class="ml-2 d-flex align-items-center justify-content-center" style="height:60px" >
      <%= "#{@customer.fist_name}" "　""#{@customer.last_name}" %>
      </div>
     </div>
  </div>
       <div class="form-inline">
    <div class="form-group">
    　<lavel>フリガナ </lavel>
      <div class="ml-2 d-flex align-items-center justify-content-center" style="height:40px" >
      <%= "#{@customer.fist_name_kana}" "　""#{@customer.last_name_kana}" %>
      </div>
     </div>
  </div>
   <div class="form-inline">
    <div class="form-group">
    　<lavel>郵便番号</lavel>
      <div class="ml-2 d-flex align-items-center justify-content-center" style="height:60px" >
      <%= "#{@customer.postal_code}" %>
      </div>
     </div>
  </div>
  <div class="form-inline">
    <div class="form-group">
    　<lavel>住所</lavel>
      <div class="ml-2 d-flex align-items-center justify-content-center" style="height:60px" >
      <%= "#{@customer.address}" %>
      </div>
     </div>
  </div>
  <div class="form-inline">
    <div class="form-group">
    　<lavel>電話番号</lavel>
      <div class="ml-2 d-flex align-items-center justify-content-center" style="height:60px" >
      <%= "#{@customer.phon_number}" %>
      </div>
     </div>
  </div>
  <div class="form-inline">
    <div class="form-group">
    　<lavel>メールアドレス</lavel>
      <div class="ml-2 d-flex align-items-center justify-content-center" style="height:60px" >
      <%= "#{@customer.email}" %>
      </div>
     </div>
  </div>
  <div class="form-inline">
    <div class="form-group">
    　<lavel>会員ステータス</lavel>
      <div class="ml-2 d-flex align-items-center justify-content-center" style="height:60px" >
        <% if @customer.is_deleted == true %>
          <div class="form-inline text-muted">
            無効
         </div>
          <% else %>
          <div class="form-inline text-success">
            有効
          </div>
          <% end %>
      </div>
     </div>
  </div>
  </div>
   <div class="form-inline">
    <div class="form-group" style="height:80px">
      <div class="actns" >
<%= link_to "編集する", edit_admin_customer_path, class: "ml-2 btn px-5  btn-success font-weight-bold d-flex"  %>
　　　</div>
  　</div>
    <div class="form-group" style="height:80px">
      <div class="actns" >
  <%= link_to "注文履歴一覧を見る", admin_orders_path, class: "ml-5 btn px-5  btn-primary font-weight-bold d-flex" %>
  　　</div>
  　</div>
  </div>
 </div>